#!/bin/sh
input=$1
g09root=$(readlink -f /usr/local/programs/common/gaussian/gaussian09/arch/amd64-pgi_10.4.0-acml)
scrhome=/scratch/$USER
scratch=/scratch/$USER/g09_$$
export WORKDIR=$PWD
export g09root=${g09root}
export LD_LIBRARY_PATH=${g09root}/g09
export GAUSS_SCRDIR=${scratch}
export GAUSS_EXEDIR=${g09root}/g09
/bin/mkdir $GAUSS_SCRDIR
cd $WORKDIR
/bin/uname -a >${input}.log
/bin/date >>${input}.log
/bin/echo >>${input}.log
/usr/bin/time -a -o ${input}.log $GAUSS_EXEDIR/g09 <${input} >>${input}.log
/bin/rm -rf $GAUSS_SCRDIR
/bin/rm -rf ${scrhome}/*.rwf
/bin/rm -rf ${scrhome}/*.scr
/bin/rm -rf ${input}.dqs
/bin/rm -rf core
