#!/bin/bash
if [ $# -lt 4 ]; then
	echo "Usage: OPT <opt file> <queue> <number of cpu> <memory per cpu>"
	echo "The opt file has to contain:"
	echo "  program=(gaussian|turbomole|vasp[-gamma,-vtst,-gamma-vtst])"
	echo "  geometry=<geometry file>"
	echo "  input=<input file>"
	exit
else
	jobname=$1
	queue=$2
	ncpu=$3
	memory=$4
	if [ -f $jobname ]; then
		. $jobname
	else
		echo "Error: opt file does not exist"
		exit
	fi
	if [ -z $program -o -z $geometry -o -z $input ]; then
		echo "Error: incorrect opt file"
		exit
	fi
fi
if [ ! -f $geometry -o ! -f $input ]; then
	echo "Error: geometry or input file does not exist"
	exit
fi
scriptdir=$(dirname $(readlink -f $0))
cat > $jobname.dqs << EOF
#!/home/hermann/local/bin/oct -q
addpath(genpath('$scriptdir'));
opt('$jobname');
delete $jobname.dqs
EOF
if [ ! -d qout ]; then
	mkdir qout
else
	rm -f qout/*
fi
if [ -z $restart ]; then
	rm -f $jobname.log
fi
if [ "$restart" == "no" ]; then
	rm -f $jobname.log
fi
if [[ "$program" =~ "vasp" ]]; then
	sp="mpi"
else
	sp="shm"
fi
command="qsub -V -l mem=$memory -cwd -e qout -o qout -pe $sp $ncpu -N $jobname -q $queue $jobname.dqs"
echo "Submitting optimization job $jobname.dqs to queue $queue"
echo "$ $command"
$command
