% converts element symbol on atomic number or vice versa. 12/04/07

function n = element(s)
	table = {'H' 'He' 'Li' 'Be' 'B' 'C' 'N' 'O' 'F' 'Ne'...
		'Na' 'Mg' 'Al' 'Si' 'P' 'S' 'Cl' 'Ar' 'K'...
		'Ca' 'Sc' 'Ti' 'V' 'Cr' 'Mn' 'Fe' 'Co' 'Ni'...
		'Cu' 'Zn' 'Ga' 'Ge' 'As' 'Se' 'Br' 'Kr' 'Rb'...
		'Sr' 'Y' 'Zr' 'Nb' 'Mo' 'Tc' 'Ru' 'Rh' 'Pd'...
		'Ag' 'Cd' 'In' 'Sn' 'Sb' 'Te' 'I' 'Xe' 'Cs'...
		'Ba' 'La' 'Ce' 'Pr' 'Nd' 'Pm' 'Sm' 'Eu' 'Gd'...
		'Tb' 'Dy' 'Ho' 'Er' 'Tm' 'Yb' 'Lu' 'Hf' 'Ta' 'W'...
		'Re' 'Os' 'Ir' 'Pt' 'Au' 'Hg' 'Tl' 'Pb' 'Bi'...
		'Po' 'At' 'Rn' 'Fr' 'Ra' 'Ac' 'Th' 'Pa' 'U'};
	if isnumeric(s)
		n = table{s};
	else
		for n = 1:length(table)
			if strcmpi(s,table{n}), return, end
		end
		error('Unknown element symbol');
	end
end

