% saves information from geom struct into POSCAR. 12/04/15

function geom2car(geom,filename)
	atoms = geom.atoms;
	ind = 1:length(atoms);
	i = 0;
	while sum(ind)
		i = i+1;
		elem{i} = atoms(ind(find(ind,1)));
		elemind{i} = find(atoms==elem{i});
		ind(elemind{i}) = 0;
	end
	elemarr = zeros(length(elem),2);
	for i = 1:length(elem)
		elemarr(i,1:length(elem{i})) = elem{i};
	end
	fid = fopen(filename,'w');	
	fprintf(fid,'POSCAR generated by geom2car\n1.0\n');
	fprintf(fid,'%13.10f %13.10f %13.10f\n',geom.abc');
	for i = 1:length(elem)
		fprintf(fid,'%s ',element(elem{i}));
	end
	fprintf(fid,'\n');
	for i = 1:length(elem)
		fprintf(fid,'%i ',length(elemind{i}));
	end
	fprintf(fid,'\n');
	fprintf(fid,'direct\n');
	xyz = geom.xyz/geom.abc;
	for i = 1:length(elem)
		for j = 1:length(elemind{i})
			fprintf(fid,'%13.10f %13.10f %13.10f\n',...
				xyz(elemind{i}(j),:));
		end
	end
	fclose(fid);
end
